INCLUDE_VERSIONS_SOURCE=true

ASDF_NODE_VERSION=18.5.0
ASDF_YARN_VERSION=latest
ASDF_GO_VERSION=1.14.3
ASDF_PHP_VERSION=7.1
ASDF_PYTHON_VERSION=3.11.4
ASDF_RUBY_VERSION=2.7.6
ASDF_REDIS_VERSION=7.0.11
#REDIS_CONFIGURE_OPTIONS
#REDIS_EXTRA_CONFIGURE_OPTIONS