INCLUDE_VERSIONS_SOURCE=true

ASDF_NODE_VERSION=14.8.0
ASDF_YARN_VERSION=1.22.15
ASDF_GO_VERSION=1.14.3
ASDF_PHP_VERSION=7.1
ASDF_PYTHON_VERSION=3.8.5
ASDF_RUBY_VERSION=2.5.1
ASDF_REDIS_VERSION=6.0.9
#REDIS_CONFIGURE_OPTIONS
#REDIS_EXTRA_CONFIGURE_OPTIONS