#!/usr/bin/env bash

source ../config.sh
source rsync.sh

SRC="$DRIVE_SOURCE_DOUBLEDOUBLE_VOLUME$DRIVE_SOURCE_DOUBLEDOUBLE_DISKSTATION/"
DEST="$DRIVE_SOURCE_REDRIGHT_VOLUME$DRIVE_SOURCE_REDRIGHT_DISKSTATION/"
RSYNC_DELETE="false"
RSYNC_LOG="true"
RSYNC_DRY="false"
RSYNC_EXCLUDE_MAC="true"

run_rsync

SRC="$DRIVE_SOURCE_DOUBLEDOUBLE_VOLUME$DRIVE_SOURCE_DOUBLEDOUBLE_BACKUP/"
DEST="$DRIVE_SOURCE_REDRIGHT_VOLUME$DRIVE_SOURCE_REDRIGHT_BACKUP/"
RSYNC_DELETE="true"
RSYNC_LOG="true"
RSYNC_DRY="false"
RSYNC_EXCLUDE_MAC="true"

run_rsync
