#!/usr/bin/env bash

source ../config.sh
source rsync.sh

# # /Assets
# SRC="$DRIVE_SOURCE_ASSETFOUR_VOLUME$DRIVE_SOURCE_ASSETFOUR_ASSETS/"
# DEST="$DRIVE_SOURCE_REDASSET_VOLUME$DRIVE_SOURCE_REDASSET_ASSETS/"
# RSYNC_DELETE="false"
# RSYNC_LOG="true"
# RSYNC_DRY="false"
# RSYNC_EXCLUDE_MAC="true"

# run_rsync

# # /RetroGames
# SRC="$DRIVE_SOURCE_ASSETFOUR_VOLUME$DRIVE_SOURCE_ASSETFOUR_GAMES/"
# DEST="$DRIVE_SOURCE_REDASSET_VOLUME$DRIVE_SOURCE_REDASSET_GAMES/"	
# RSYNC_DELETE="false"
# RSYNC_LOG="true"
# RSYNC_DRY="false"
# RSYNC_EXCLUDE_MAC="true"

# run_rsync

# /Tabletop
SRC="$DRIVE_SOURCE_ASSETFOUR_VOLUME$DRIVE_SOURCE_ASSETFOUR_TABLETOP/"
DEST="$DRIVE_SOURCE_REDASSET_VOLUME$DRIVE_SOURCE_REDASSET_TABLETOP/"	
RSYNC_DELETE="true"
RSYNC_LOG="true"
RSYNC_DRY="false"
RSYNC_EXCLUDE_MAC="true"

run_rsync
