#!/usr/bin/env bash

source ../config.sh
source rsync.sh

SRC="$DRIVE_SOURCE_DOUBLEDOUBLE_VOLUME$DRIVE_SOURCE_DOUBLEDOUBLE_DISKSTATION/"
DEST="$DRIVE_SOURCE_REDULTRA_VOLUME$DRIVE_SOURCE_REDULTRA_DISKSTATION/"
RSYNC_DELETE="false"
RSYNC_LOG="true"
RSYNC_DRY="false"
RSYNC_EXCLUDE_MAC="true"

run_rsync

SRC="$DRIVE_SOURCE_DOUBLEDOUBLE_VOLUME$DRIVE_SOURCE_DOUBLEDOUBLE_BACKUP/"
DEST="$DRIVE_SOURCE_REDULTRA_VOLUME$DRIVE_SOURCE_REDULTRA_BACKUP/"
RSYNC_DELETE="true"
RSYNC_LOG="true"
RSYNC_DRY="false"
RSYNC_EXCLUDE_MAC="true"

run_rsync
