# Load the shell dotfiles, and then some:
# * bash_paths can be used to extend `$PATH`.
# * bash_extra can be used for other settings you don’t want to commit.
for file in ~/.{bash_paths,bash_exports,bash_prompt,bash_aliases,bash_functions,bash_extra}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
  shopt -s "$option" 2> /dev/null;
done;

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
#[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;

# Check for brew
if type brew &>/dev/null; then
  HOMEBREW_PREFIX="$(brew --prefix)"

  # Add bash completion
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
      [[ -r "$COMPLETION" ]] && source "$COMPLETION"
    done
  fi

  HOMEBREW_ASDF_PREFIX="$(brew --prefix asdf)"
  if [[ -r "${HOMEBREW_ASDF_PREFIX}/libexec/asdf.sh" ]]; then
    source "${HOMEBREW_ASDF_PREFIX}/libexec/asdf.sh"
  fi
fi
